### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by skn123** [mUogoro/padenti#2]
What are the license terms? LGPL or GPL? Can you please display that on the page? The files say that it is LGPL while the page says it is GPL.

**Comment by mUogoro** [comment]
The license is LGPLv3, it's now clearly stated in the README.md

**Comment by skn123** [comment]
![image](https://user-images.githubusercontent.com/4594354/54067138-4d24db00-4262-11e9-9f58-3a9ef68ec46f.png)
Looks like this has not changed
